<?
if($_SERVER['REQUEST_URI'] !== '/TWC/bc/styleguide/') {
  include($_SERVER['DOCUMENT_ROOT']. '/TWC/bc/core/includes/header.php');
}
?>

<div class="shadow-content">

  <figure class="shadow-1">
    <img src="images/winter-banner-internet-overview-ALL-0119.jpg">
  </figure>

	<div class="box shadow-1">
		<h3>Box Shadow 1</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio expedita sequi quam aperiam voluptate incidunt perspiciatis dolores. Impedit, culpa, dolorem quis enim suscipit id quam odio nam assumenda vel facere iste non! Reprehenderit, enim, quo vel temporibus sapiente repellat et quibusdam atque eveniet laborum accusantium dolor porro sed consequuntur quas sint eos natus perspiciatis similique soluta voluptatibus est mollitia tempora illo aliquid eius totam ratione maiores modi sunt quisquam asperiores omnis nemo placeat magni officia quidem. Perferendis, tempore, repellat unde cum nemo eveniet excepturi nesciunt odit consectetur illum ipsa doloremque quo nihil fugiat sed. Sed, assumenda, libero vitae deserunt provident officia voluptas doloribus rem nemo reiciendis molestiae amet minima nisi velit facilis asperiores expedita! Placeat, odit labore aut deleniti soluta. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex, optio mollitia cumque eligendi libero fuga quae odio dolorem at nam nostrum consequuntur tempore quia voluptatum quis explicabo doloribus! Nisi, natus nesciunt harum error dignissimos pariatur dolore a tempore perferendis perspiciatis expedita aspernatur corporis sed vel eligendi veritatis animi totam quasi enim hic quaerat! Earum quia illum fugiat quo error blanditiis officia beatae libero incidunt minima. Impedit, nihil ipsa nulla ea asperiores labore dicta laudantium iste et. Deleniti officiis debitis esse porro repellendus. Expedita, molestias, nulla enim repellat vitae itaque reiciendis dolor neque eos consectetur sed perspiciatis alias dolores distinctio necessitatibus maiores quidem vero quisquam error non architecto quia doloribus. Repellat, error, architecto, repudiandae voluptate velit autem quasi earum illum accusamus eos possimus tempora quibusdam eligendi animi facilis! Maiores, aspernatur, nam ut accusantium labore ipsam iste temporibus error. Animi quaerat illo amet! Veritatis, nulla nihil accusantium esse omnis culpa possimus! Provident.</p>
	</div>

  <!-- <div class="box shadow-2">
    <h3>Box Shadow 2</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor, fugit, cupiditate at fuga rem ut dolorum veritatis sit. Quod ullam assumenda vel animi sunt. Aut, amet, fuga magni sint harum doloremque libero similique dolores vitae quo dolorem quaerat dolorum soluta ut quis minima officia saepe. Architecto, dolor, recusandae obcaecati dolore numquam ut aut molestiae quis quaerat ad quam fugit a facilis cupiditate dolorum molestias impedit corporis distinctio cum voluptatum optio praesentium delectus perferendis at doloremque reiciendis minus sed facere inventore qui quisquam excepturi eos eius repellendus deleniti assumenda quae. Et, ipsa sapiente voluptates error est sed doloremque voluptas distinctio nam quaerat. Officiis, quod minima quisquam alias nulla eligendi blanditiis mollitia voluptates! Recusandae, vero sunt aut facilis accusamus dolore architecto? Tempora, accusantium, minus, deserunt distinctio perspiciatis vitae et ipsum impedit temporibus dolorum quis cumque recusandae vero dolore maiores tenetur itaque voluptate dolor aperiam inventore rem similique adipisci molestiae provident asperiores repellat nostrum neque! Repellendus, repudiandae dolor vitae suscipit impedit sed mollitia esse fugiat? Quasi, odio, alias, in aut nisi sapiente id animi repellat illum dicta iusto nesciunt corporis enim! Sunt, ullam excepturi cupiditate quaerat voluptatem quod dolor perspiciatis expedita officiis vitae corporis assumenda quidem nostrum repellendus dignissimos. Asperiores, sint, repudiandae, vel, et tempore magnam consequatur assumenda ea quod distinctio iste perferendis error nesciunt officia blanditiis laborum molestias officiis. Illo, libero, nesciunt, animi vel laborum vero doloribus repellat voluptatem reprehenderit porro voluptates debitis deserunt neque doloremque maiores magnam dicta! Debitis, alias, beatae, iure molestiae laboriosam ratione ut commodi natus cupiditate accusamus eius dicta fugit modi culpa explicabo necessitatibus reiciendis minima temporibus neque sequi minus enim tempora voluptate voluptatibus accusantium iste dolor officiis repudiandae recusandae? Quibusdam, voluptate, beatae, at modi nulla id natus facere reprehenderit voluptatum excepturi recusandae quae impedit dolores debitis eius nobis explicabo corporis velit aliquid quisquam quaerat nam asperiores porro?</p>
  </div>
  <div class="box shadow-3">
    <h3>Box Shadow 3</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, labore eius dolorem aperiam! Dolores, minus, quidem, autem distinctio pariatur reprehenderit perspiciatis nemo veritatis commodi totam iusto molestias. Similique, sed, expedita, debitis, saepe blanditiis unde hic eligendi dolorum necessitatibus provident enim deleniti officiis voluptatum culpa odit mollitia labore nostrum amet quae qui. Corrupti, hic eius ex qui a rem eveniet nesciunt deserunt esse cumque. Omnis, eaque, quae necessitatibus ratione iste sed quasi corporis magni soluta ipsum expedita maiores quos cum rem ab distinctio laborum quam perferendis similique possimus in harum enim beatae odit sunt accusantium quidem illo nostrum asperiores tempora cumque repudiandae dignissimos inventore doloremque eveniet porro error a incidunt provident unde fugiat aliquam! Numquam, quibusdam, voluptatem, tempora, nostrum totam est eius quam voluptatibus sed fuga placeat fugit labore voluptatum quae magni non corporis nam sapiente a quo adipisci facilis inventore veniam necessitatibus reprehenderit sint dignissimos earum. Fugit, explicabo, assumenda, ipsa, at reiciendis officia fugiat ipsum ea distinctio cum asperiores ducimus et natus exercitationem nesciunt corporis eligendi facilis repellat sint quaerat reprehenderit saepe voluptates temporibus nam optio consectetur quam praesentium. Dolorum, consequatur molestiae minima deserunt quo. Atque, minus, earum, laudantium ad deleniti fugit eius temporibus debitis sed vel dolores vero ea. Molestiae, corrupti, error autem illum cumque placeat in quod molestias officia repudiandae? Facilis, et consectetur recusandae nulla expedita quis facere illum aliquid dolores explicabo eum officiis voluptatum architecto impedit praesentium culpa tempore magnam accusamus eligendi quos soluta consequuntur repudiandae ea enim distinctio nihil temporibus alias accusantium ab fuga. Quidem, veniam ea vitae quis autem repudiandae quos cum quo quod quas. Est, ex, vitae, accusantium natus necessitatibus excepturi tenetur magni dolor ut atque quasi id dignissimos saepe sint laborum facere consequuntur. Distinctio, ipsum, molestias quae vero veritatis quia labore perferendis harum voluptates temporibus corporis ut dolore quas possimus incidunt non ducimus. Quae, officiis, in, quo, distinctio magnam possimus asperiores doloribus incidunt dolore a deleniti vitae illum vel. Hic, temporibus, eaque odio aperiam quis iusto dolorum necessitatibus vitae quidem culpa iste qui sapiente voluptas officiis ipsa expedita adipisci consequatur minima quasi enim provident vero tempore quam eos quisquam nulla magni perferendis facere.</p>
  </div>
  <div class="box shadow-4">
    <h3>Box Shadow 4</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, inventore, pariatur consequuntur numquam sint modi enim quas minima velit nesciunt eaque soluta eius molestias similique laudantium aut consequatur ex praesentium aliquam deleniti accusamus dignissimos cum ut reprehenderit veniam quod hic consectetur commodi vitae tenetur. Sunt, dolorum, vero pariatur error quisquam aperiam recusandae impedit officia sit ad distinctio perspiciatis dolores sapiente molestias rem quibusdam voluptatem nisi in ut officiis tempore omnis dolore harum architecto ipsum itaque voluptate iusto culpa non! Fuga, optio, illum ipsum commodi quis consequuntur doloremque quos vero reiciendis ea accusantium quasi nulla. Error, tempora, velit, laboriosam in asperiores iusto perspiciatis facilis natus consectetur nulla architecto expedita sint a dolorum aut! Dicta corporis magnam aut voluptatem pariatur consectetur quia vitae doloremque praesentium dolores! Aspernatur, repellat veritatis tempora autem illum qui iure excepturi voluptatem explicabo neque beatae consequatur eaque sit totam ab rem vero eum in natus accusantium consequuntur harum iusto temporibus aut aperiam ducimus officia? Blanditiis, saepe, aperiam reprehenderit error odio delectus natus quae iste nam suscipit placeat assumenda earum mollitia molestias ex consequuntur quibusdam adipisci at dolores nihil? Incidunt, iure modi possimus atque maiores cupiditate labore quia sed. Voluptatum, in ut suscipit obcaecati earum consequuntur id dignissimos reiciendis.</p>
  </div>
 -->
</div>

<?
if($_SERVER['REQUEST_URI'] !== '/TWC/bc/styleguide/') {
  include($_SERVER['DOCUMENT_ROOT']. '/TWC/bc/core/includes/footer.php');
}
?>