<div class="abf">





















<div class="default disclaimerConfiguration">

































        <div class="disclaimer js-viewMore-initialized active" data-view-more="{&quot;viewMore&quot; : &quot;View More&quot;, &quot;viewLess&quot; : &quot;View Less&quot;}">
            <div class="preview-text">

                <div class="twc-base-text-tooltips previewText"><p>Additional charges apply for equipment, installation, taxes &amp; fees, broadcast, sports programming, activation and other surcharges, Directory Assistance, Operator Services, International calls outside of the calling area and other one-time charges. By enrolling in this promotion, customer agrees to be bound by the terms of TWC’s Subscriber Agreement which can be found at <a href="http://help.twcable.com/twc_sub_agreement.html" target="_blank">http://help.twcable.com/twc_sub_agreement.html</a>. Triple Play offers expire 6/18/16 and are available to residential new and existing Single Play customers. Triple Play price will increase $20 per month for months 13-24. After 24 months, regular rates in effect at that time apply. Lease of at least one Whole House HD-DVR and one WH DVR compatible Set Top Box required. Standard TV for $39.99 available for 12 months; in months 13-24, price will increase to $44.99; after month 24, regular rates in effect at that time apply. TV offer expires 6/30/16 and is available to current residential Double Play (Internet/TWC Phone); offer may not be combined. After 1 year, regular rates in effect at that time apply. HBO®, Cinemax®, SHOWTIME® and STARZ® premium bundle offer is available to new customers and current Time Warner Cable customers who already have or are adding TV service and a set-top box to their accounts. To qualify, current customers cannot already subscribe to two or more premiums. The rate for this offer is $29.99 per month for 12 months. After 1 year, regular rates in effect at that time will apply. Free Installation applies to Easy Connect Kit through 6/18/16. Free Installation does not apply to National West and Former New Wave and Former Insight locations. All services not available in all areas. Not all equipment supports all services. Subject to change without notice. Some restrictions apply. Offers may not be combined.</p>
</div>

            </div>


                <div class="remaining-text" style="display: block;">

                    <div class="twc-base-text-tooltips remainingText"><p>To receive all TV services, Preferred TV, remote and lease of a Set-Top box are required. Some services are not available to CableCARD™ customers. In some areas, a Digital Programming fee may apply to each additional box.</p>
<p>The Better Guarantee is a thirty-day money-back guarantee that applies to TV, Phone and/or Internet monthly recurring charge and standard installation charge. TWC must receive cancellation request for all eligible services within 30 days after installation. Return of all leased equipment required. Lease of a modem or purchase of a compatible modem required for Internet service. Current compatible modems can be found at <a target="_blank" href="http://www.twc.com/compatiblemodems">twc.com/compatiblemodems</a>.</p>
<p><b><u>$300 Reward Card:</u></b> $300 Reward Card offer expires 6/30/16.&nbsp;Offer available in California, Hudson Valley, New York City and New Jersey Time Warner Cable service areas only to any new subscribers or existing high speed internet (HSD) only subscribers who switch and purchase an $89 or higher Triple Play bundle. Customers in other Time Warner Cable service areas who purchase a $109 or higher Triple Play bundle are also eligible for the $300 Reward Card offer. Customers must remain active, in good standing and must maintain all services for a minimum of 90 days after installation.</p>
<p>Customer must register within 30 days of installation, or by 11:59 p.m. PDT on 7/31/16, (whichever comes sooner) at <a target="_blank" href="http://www.twc.com/betterreward">www.twc.com/betterreward</a> with the redemption code which you will receive via email and/or postcard and upload a bill from their previous paid video, HSD or phone service provider issued within the last 90 days showing the service they are cancelling as proof of switch. Customer's name and/or address on previous provider's bill must match name and/or address on Time Warner Cable installation order. Eligible paid video providers do not include online-only video subscription providers and paid phone providers do not include cellular providers. See <a target="_blank" href="http://www.twcbetterreward.com/Terms">www.twcbetterreward.com/Terms</a> for more information and complete terms and conditions. Reward Card will be mailed approximately 4-6 weeks after the 90 day period. Reward cards may be subject to separate terms and conditions imposed by issuer. Limit one (1) Reward Card per eligible residential service and this offer may not be combined with any other offers.</p>
<p><b><u>TWC TV® Roku Trial:</u></b> Offer expires 6/18/16.&nbsp;Single Play offers are available to residential existing Standard Internet or above customers in good standing in NYC/NJ serviceable areas. Double Play offers are available to new Standard Internet or above and Starter TV or above customers, in NYC/NJ serviceable areas. Additional customer-supplied Roku 3 or other TWC TV supported devices are required for additional TVs. A complete list of TWC TV supported devices may be found at <a target="_blank" href="http://www.twc.com/twctv">twc.com/twctv</a>. Not available to bulk residential customers. By enrolling in this promotion, customer agrees to be bound by the terms of TWC’s Subscriber Agreement available at <a target="_blank" href="http://help.twcable.com/html/twc_sub_agreement.html">http://help.twcable.com/html/twc_sub_agreement.html</a> and must agree to TWC TV® Roku Trial Agreement at <a target="_blank" href="https://twcabletrial.com">https://twcabletrial.com</a>. DVR, Video On Demand for purchase, sports league passes, adult services, Start Over, TV en Espanol, and TV en Espanol Mas are not available. A DOCSIS 3.0 modem and home WiFi are required. Additional charges apply for equipment, broadcast, sports programming, and other surcharges, taxes &amp; fees, and for new Internet customers, installation charge may apply. Lease of a modem or purchase of a compatible modem required for Internet service. Currently compatible modems can be found at <a target="_blank" href="http://www.twc.com/compatiblemodems">twc.com/compatiblemodems</a>. After promotional period, regular monthly rates will apply. TWC TV Roku Trial term subject to change.</p>
<p><b>TV:</b> HDTV and HD Set-Top Box are required to receive HD service. TWC TV® requires Starter TV, iPad and/or iPhone with iOS 7.0, Kindle Fire HD/HDX and/or Android 2.3 and/or Android 2.3 on smartphones and Android 4.0 or higher and WiFi connection. Start Over® is available on select shows from participating networks. As a condition of service, you may be required to have equipment for every TV in your home. TWC authorized modem required for in home viewing and minimum 1.5 Mbps connection recommended for out of home viewing. Some functions require compatible Set-Top box or DVR. Programming is subject to availability and the video package to which you subscribe. Not all equipment supports all services. HDTV and HD set-top box are required to receive HD service. &nbsp;</p>
<p>Must subscribe to both Preferred TV and Phone to get Caller ID on TV. Caller ID on TV is not available in all areas.</p>
<p>Pay-per-View programming is available to Existing customers only; scheduling subject to change. HD Events are not available in all areas. Pay-Per-View events and HD Pay-Per-View events are optional services available for an incremental charge. Prices do not include taxes or franchise fees. Some restrictions apply. © 2016 Zuffa, LLC. All rights reserved. All WWE programming, talent names, images, likenesses, slogans, wrestling moves, trademarks, logos and copyrights are the exclusive property of WWE and its subsidiaries. All other trademarks, logos and copyrights are the property of their respective owners. © 2016 WWE. All Rights Reserved. Card subject to change. Canelo vs Khan ©2016 HBO Pay-Per-View®, a division of Home Box Office, Inc.® and Golden Boy Promotions, Inc. All rights reserved. HBO PPV®, HBO® and all related channels and service marks are the property of Home Box Office, Inc. Card subject to change.</p>
<p><b>Internet:</b> Access to WiFi hotspots is available to customers with minimum Standard or Extreme Internet. Actual speeds may vary. Not available in all areas. Some restrictions may apply. Some Internet services may include Home WiFi and may require installation charges.</p>
<p><b>Phone:</b> Additional charges apply for surcharges, taxes, fees, Directory Assistance, Operator Services and International calls outside of the calling area. [TWC Phone does not include back‐up power and, as in the case with an electric‐powered home cordless phone, should there be a power outage, TWC Phone, including the ability to access 9‐1‐1 services, may not be available. 8-Hour back-up power available for a fee.]</p>
<p><i>New York residents:</i> 25.97% of the charge for your BCP Unlimited phone service is attributable to interstate or international telecommunications service and is excluded from New York sales tax.</p>
<p><i>Kentucky residents:</i> For purposes of calculating the amount of Kentucky Utility Gross Receipts Tax (School Tax), 25.97% of the charge for the phone service is attributable to interstate activity and is excluded from KY School Tax.</p>
<p><b>Phone 2 Go App:</b> Phone 2 Go requires TWC Phone service, a TWC ID, a compatible device running iOS 6.0, Android 4.1 or higher and a cellular or Wi-Fi data connection. Phone 2 Go may not be available in all areas. Subject to change without notice. Some restrictions apply.</p>
<p><b>Payments:</b> If you discontinue recurring payments within your first year of service, a $50 deposit will be added to your account.</p>
<p>Time Warner Cable and the eye/ear logo are trademarks of Time Warner Inc. Used under license. HBO GO® and MAX GO® are only accessible in the U.S. and certain U.S. territories where a high speed internet connection is available. Minimum 3G connection is required for viewing on mobile devices. HBO® and CINEMAX® are service marks of Home Box Office Inc. SHOWTIME® and related marks are trademarks of Showtime Networks Inc., a CBS Company. You must be a subscriber of SHOWTIME® to receive SHOWTIME ANYTIME®. Showtime Anytime is available through participating TV providers. Showtime Anytime is intended for viewing solely in the United States and its territories and possessions. STARZ® and related channels and service marks are the property of Starz Entertainment, LLC. All other trademarks are property of their respective owners. ©2016 Time Warner Cable Inc. All rights reserved. To order any services not available online, <a target="_blank" href="/content/twc/en/support/contact-us.html">contact us</a>.</p>
<p><u>For Hawaii Customers Only.</u></p>
<p>The Better Guarantee is a thirty-day money-back guarantee that applies to TV, Phone and/or Internet monthly recurring charge and standard installation charge. TWC must receive cancellation request for all eligible services within 30 days after installation. Return of all leased equipment required.</p>
<p>* Offers expire 6/18/16 and are available to existing residential customers. By enrolling in this promotion, customer agrees to be bound by the terms of TWC’s Subscriber Agreement which can be found at <a target="_blank" href="http://help.twcable.com/twc_sub_agreement.html">http://help.twcable.com/twc_sub_agreement.html</a>. Additional charges apply for equipment, installation, taxes &amp; fees, broadcast, sports programming, activation and other surcharges, Directory Assistance, Operator Services, International calls outside of the calling area and other one-time charges. After promotional period, regular monthly rates will apply. You may cancel anytime by calling 643-2337. Free Installation applies to Easy Connect Kit through 6/18/16. All services may not be available in all areas. Not all equipment supports all services. Subject to change without notice. Some restrictions apply. Offers may not be combined.</p>
<p>Subscription to a qualifying Time Warner Cable Triple Play and proof of switch from previous provider are required to receive a Visa Reward Card. Customers must be in good standing and maintain all services for 90 days. To register go to switchto.oceanic.com. Use promo code: Oceanic100, Oceanic 200 or Oceanic300.</p>
<p>The Visa Reward Card is issued by The Bancorp Bank pursuant to a license from Visa U.S.A. Inc. The Bancorp Bank; Member FDIC. The Bancorp Bank is not affiliated in any way with Time Warner Cable and does not endorse or sponsor this offer. The Visa Reward Card is distributed and serviced by Interactive Communications International, Inc. as an authorized agent of either ITC Financial Licenses, Inc. or IH Financial Licenses, Inc. dependent upon the state where this Card is purchased. Terms and conditions apply. The Visa Reward Card may be used in the U.S. and District of Columbia everywhere Visa debit cards are accepted. The Card may not be used outside of the U.S. or the District of Columbia including Internet and mail or telephone order merchants outside of the U.S. or the District of Columbia.<br>
</p>
<p><b>$100 Reward Card:</b> Offer expires 6/30/16. Subscription to a qualifying Time Warner Cable service or package and proof of switch from previous provider are required to receive $100 Visa Reward Card. Offer available to NEW and Existing residential customers who reside in the specified Oceanic Time Warner Cable serviceable areas and who are adding Oceanic Time Warner Cable's advertised offer. Reward card promotion available to new Digital TV, Extreme Internet or higher, or Digital Basic TV and Ultimate 100 package customers or existing Oceanic Time Warner Cable customers adding the Digital Basic TV, and Ultimate 100 and TWC Phone offer, Digital TV and Ultimate 100 offer, Digital Basic TV and Ultimate 100 offer or Ultimate 100 Internet tier or higher. Customers who qualify for a Visa Reward Card must remain in good standing and maintain all services for 90 days after installation. Reward Card will be mailed approximately 4-6 weeks after the 90-day period. To register go to <a href="http://www.switchto.oceanic.com" target="_blank">switchto.oceanic.com</a>. Use promo code: Oceanic100. Full terms &amp; conditions at <a href="http://www.switchto.oceanic.com" target="_blank">www.switchto.oceanic.com</a>. Reward Cards may be subject to issuer’s separate terms &amp; conditions. Limit one Reward Card per eligible residential service and this offer may not be combined with any other offers. To receive Reward Card, register within 30 days of installation, or by 11:59 p.m. EST on 08/31/16 03/31/16 (whichever comes sooner), at <a href="http://www.switchto.oceanic.com" target="_blank">www.switchto.oceanic.com</a>.<br>
</p>
<p><b>$200 Reward Card:</b> Offer expires 6/30/16. Subscription to a qualifying Time Warner Cable service or package and proof of switch from previous provider are required to receive $200 Visa Reward Card. Offer available to NEW and Existing residential customers who reside in the specified Oceanic Time Warner Cable serviceable areas and who are adding Oceanic Time Warner Cable's advertised offer. Reward card promotion available to new Digital Basic TV, Ultimate 100 Internet and TWC Phone customers, Digital TV and Ultimate 100 customers, or existing Oceanic Time Warner Cable customers adding the Digital Basic TV, Ultimate 100 Internet and TWC Phone offer or Digital TV, Ultimate 200 and TWC Phone offer. Customers must be in good standing and maintain services must be installed for 90 days and account must be in good standing. To register go to <a href="http://www.switchto.oceanic.com" target="_blank">switchto.oceanic.com</a>. Use promo code: Oceanic200. Reward Card will be mailed approximately 4-6 weeks after the 90-day period. Full terms &amp; conditions at <a href="http://www.switchto.oceanic.com" target="_blank">www.switchto.oceanic.com</a>. Reward Cards may be subject to issuer’s separate terms &amp; conditions. Limit one Reward Card per eligible residential service and this offer may not be combined with any other offers. To receive Reward Card, register within 30 days of installation, or by 11:59 p.m. EST on 8/31/16 (whichever comes sooner), at <a href="http://www.switchto.oceanic.com" target="_blank">www.switchto.oceanic.com</a>.<br>
</p>
<p><b>$300 Reward Card:</b> Offer expires 6/30/2016. Offer available only to NEW residential customers who reside in the specified Oceanic Time Warner Cable serviceable areas and who are adding Oceanic Time Warner Cable's advertised offer. Reward card promotion available to new Standard Video, Extreme Internet and TWC Phone customers. Oceanic Time Warner Cable customer must add a minimum of THREE Product Service Units (Standard Video, Extreme Internet, TWC Phone). Services must be installed for 90 days and account must be in good standing. Limit one (1) reward card per household. This offer may not be combined with any other offer. Reward card eligibility expires 30 days after installation of service(s) or by 11:59 p.m. HST on 7/29/16 (whichever comes sooner). <a class="modal rteModalGeneric js-modal-initialized" href="/content/modals/checkout/hawaii-valid-locations/_jcr_content.content.html">See list of locations where this offer is valid.</a></p>
<p>To qualify for the reward card offer, you must submit one of the following for each provider you previously had service with:</p>
<p>• Your final bill(s) detailing the service(s) you are cancelling. Final bill must be dated within sixty (60) days from the date of your Oceanic TWC service installation date, or<br>
• Your regular monthly bill(s) dated no earlier than sixty (60) days prior to your Oceanic TWC service installation date</p>
<p>Proof must be submitted within thirty (30) days of Oceanic Time Warner Cable service installation date. You may send it in via:</p>
<p>• Mail in an envelope with proper postage affixed to: Switch to TWC, PO Box 894530, Mililani, HI 96789.<br>
• Email: <a href="mailto:Switch2Oceanic@twcable.com" target="_blank">Switch2Oceanic@twcable.com</a><br>
• Fax toll free: 1-855-249-2447</p>
<p>Copy of customer's previous provider's bill must match at least one of the Oceanic Time Warner Cable service(s) that customer has installed. Customer's name or spouse’s last name and address on previous provider's bill must match name and address on Oceanic Time Warner Cable installation order.</p>
<p>Charges may apply for installation, taxes, fees and one-time charges.&nbsp; Offer is not available to customers with past due balances with Oceanic Time Warner Cable, defined as any money owed in the past 30-60 days or customers who have been disconnected for non-payment in the twelve (12) month period preceding this offer. Reward cards may be subject to separate terms and conditions imposed by issuer. A service fee of $2.50 per month beginning the 7th month from the date of activation will be charged to any remaining balance (except where prohibited by law). Your card will arrive already activated and may have been activated up to two (2) months prior to receipt. Reward cards will be delivered only to an address in the United States. Offer available while supplies last. You must be an active Oceanic Time Warner Cable customer when reward card is processed. Please allow up to eight (8) weeks for processing and shipping of reward cards. Oceanic Time Warner Cable will determine at its discretion the reward card retailer and is not responsible for maintenance of reward card. Refer to Cardholder Agreement.</p>
<p>By participating in the offer, participants agree to be bound by these Terms and Conditions and the decisions of Oceanic Time Warner Cable which are final and binding. Participants are responsible for ensuring that they are permitted, without restriction, to cancel their current service and are solely responsible for any fees, charges or other expenses which may be associated with any such cancellation.</p>
<p>Oceanic Time Warner Cable reserves the right in its sole discretion to modify, suspend or terminate the offer. All materials submitted in connection with this offer become property of Time Warner Cable and are non-returnable. Forged or fraudulent requests, bills or documents of any kind not obtained through authorized channels will be void.Oceanic Time Warner Cable has no obligation to acknowledge or redeem any requests that are not in compliance with these Terms and Conditions. Invalid or duplicate requests will not be honored.</p>
<p>Some restrictions may apply. All services may not be available in all areas. Oceanic Time Warner Cable reserves the right to discontinue any feature at any time. Rates are subject to change without notice.</p>
<p>Time Warner Cable and the eye/ear logo are trademarks of Time Warner Inc. Used under license. All other trademarks are property of their respective owners. ©2016 Time Warner Cable Enterprises LLC. All Rights Reserved.</p>
<p><b>TV:</b> To receive all TV services, Digital TV, remote and lease of a Set-Top box are required. As a condition of service, you may be required to have equipment for every TV in your home. HDTV and HD Set-Top box are required to receive HD service. Some services are not available to CableCARD™ customers. Some functions require compatible set-top box or DVR. Enhanced Whole House and Whole House DVR services are optional services available for an incremental charge. Lease of at least one additional Whole House DVR compatible Set-Top Box required to receive Whole House service. Actual recording capacity may vary. TWC TV® requires Basic TV, iPad or iPhone with iOS 7.0, Kindle Fire HD/HDX and/or Android 2.3 and/or Android 2.3 on smartphones and Android 4.0 or higher and WiFi connection. Start Over® is available on select shows from participating networks. As a condition of service, you may be required to have equipment for every TV in your home. TWC authorized modem required for in home viewing and minimum 1.5 Mbps connection recommended for out of home viewing. Some functions require compatible set-top box or DVR. Programming is subject to availability and the video package to which you subscribe.. Not all equipment supports all services. HDTV and HD set-top box are required to receive HD service. Must subscribe to both Digital TV and Phone to get Caller ID on TV. Caller ID on TV is not available in all areas.</p>
<p>Pay-per-View programming is available to Existing customers only. Programming, pricing, and scheduling subject to change. HD Events are not available in all areas. Pay-Per-View events and HD Pay-Per-View events are optional services available for an incremental charge. Prices do not include taxes or franchise fees. Some restrictions apply. ©2016 Zuffa, LLC. All rights reserved. All WWE programming, talent names, images, likenesses, slogans, wrestling moves, trademarks, logos and copyrights are the exclusive property of WWE and its subsidiaries. All other trademarks, logos and copyrights are the property of their respective owners. © 2016 WWE. All Rights Reserved. Card subject to change. Canelo vs Khan ©2016 HBO Pay-Per-View®, a division of Home Box Office, Inc.® and Golden Boy Promotions, Inc. All rights reserved. HBO PPV®, HBO® and all related channels and service marks are the property of Home Box Office, Inc. Card subject to change.</p>
<p><b>Internet:</b> Lease of a modem or purchase of a compatible modem required for Internet service. Current compatible modems can be found at <a target="_blank" href="http://twc.com/compatiblemodems">twc.com/compatiblemodems</a>. Access to WiFi hotspots is available to residential customers with Extreme Internet or higher. Actual speeds may vary. Not available in all areas. Some restrictions may apply. Some Internet services may include Home WiFi and may require installation charges.</p>
<p><b>Phone:</b> Additional charges apply for surcharges, taxes, fees, Directory Assistance, Operator Services and&nbsp;International calls outside of the calling area. [TWC Phone does not include back‐up power and, as in the case with an electric‐powered home cordless phone, should there be a power outage, TWC Phone, including the ability to access 9‐1‐1 services, may not be available. 8-Hour back-up power available for a fee.]</p>
<p><b>Phone 2 Go App:</b> Phone 2 Go requires TWC Phone service, a TWC ID, a compatible device running iOS 6.0, Android 4.1 or higher and a cellular or Wi-Fi data connection. Phone 2 Go may not be available in all areas. Subject to change without notice. Some restrictions apply.</p>
<p><b>Payments: </b>If you discontinue recurring payments within your first year of service, a $50 deposit will be added to your account.</p>
<p>Time Warner Cable and the eye/ear logo are trademarks of Time Warner Inc. Used under license. HBO GO® and MAX GO® are only accessible in the U.S. and certain U.S. territories where a high speed internet connection is available. Minimum 3G connection is required for viewing on mobile devices. HBO® and CINEMAX®&nbsp;and related channels and service marks are the property of Home Box Office Inc.&nbsp;You must be a subscriber of SHOWTIME® to receive SHOWTIME ANYTIME®. SHOWTIME ANYTIME® is available through participating TV providers. SHOWTIME ANYTIME® is intended for viewing solely in the United States and its territories and possessions. © 2016 Showtime Networks Inc. All rights reserved. SHOWTIME® and related marks are trademarks of Showtime Networks Inc., a CBS Company. STARZ Play is only accessible in the U.S. and certain U.S. territories and requires a high speed internet connection (a minimum 3G connection is required to use on an authorized mobile device). The Play services are included with a subscription through participating cable, satellite and telco television providers. STARZ® and related service marks are the property of Starz Entertainment, LLC. All other trademarks are property of their respective owners. ©2016 Time Warner Cable Inc. All rights reserved. To order any services not available online, <a target="_blank" href="/content/twc/en/support/contact-us.html">contact us</a>.<br>
</p>
</div>

                </div>
                <a href="#" class="view-toggle">View Less</a>

        </div>


</div>


</div>